### ISSUE TITLE
Create a gitignore file

### ISSUE THREAD

**Issue by AdrianGjerstad** [commsdevcpp/cgiscripting#6]
There should really be a `.gitignore` file for any project using Git. This is no exception.

All that it needs to contain is compensation for vim, C++ compilation, `.DS_Store`, etc.

**Comment by nicholasbus** [comment]
Hi, I could get this done if you specify what exactly to include in the ```.gitignore``` 😀

**Comment by AdrianGjerstad** [comment]
Thank you! In the gitignore file, we need to ignore vim swap files (see github vim gitignore), any `*.out`, `*.o`, or other g++ related binary files (this is a header-only library, so object files may not be needed). Optionally, it would also be good to have a mac `.DS_Store` entry, just so that other possible macOS contributors don't end up worrying about pulling up the repository in Finder.

Additionally, if you so wish, comments (bash-style `# ...`) would be much appreciated.

Thank you again!

**Comment by AdrianGjerstad** [comment]
@all-contributors please add @nicholasbus for maintenance

**Comment by AdrianGjerstad** [comment]
solved by #12
